services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hmx-backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/hmx.db:/app/hmx.db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hmx-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
